<?php

namespace GroupBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForBlog($postId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.pub = :post_id')
            ->addOrderBy('c.publishdate')
            ->setParameter('post_id', $postId);
        return $qb->getQuery()
            ->getResult();
    }
}
