<?php

namespace GroupBundle\Repository;

/**
 * GroupsMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsMembersRepository extends \Doctrine\ORM\EntityRepository
{
}
