<?php

namespace GroupBundle\Repository;

/**
 * GroupeImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeImageRepository extends \Doctrine\ORM\EntityRepository
{
}
