<?php

namespace GroupBundle\Repository;

/**
 * SignalgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
