<?php

namespace MusicBundle\Repository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function Others($user)
    {
        $req = $this->getEntityManager();
        return $req->createQuery(" select p from MusicBundle:Playlist p where p.owner != :key")
            ->setParameter('key', $user)
            ->getResult(); //model nom du table dans BDD
        //return $req->getResult();

    }
}
