<?php

namespace BonPlansBundle\Repository;

/**
 * BonPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonPlanRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM BonPlansBundle:BonPlan e
                WHERE e.name LIKE :str'
            )
            ->setParameter('str', '%' . $str . '%')
            ->getResult();
    }

    public function findByCategorie($idCategorie)
    {
        $query = $this->getEntityManager();
        return $query->createQuery('SELECT b FROM BonPlansBundle:BonPlan p WHERE b.categorie=:t')
            ->setParameter('t', $idCategorie)
            ->getResult();
    }
}
