<?php

namespace BonPlansBundle\Repository;

/**
 * RatingBonPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingBonPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
