<?php

namespace EventBundle\Repository;

/**
 * CalendarEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends \Doctrine\ORM\EntityRepository
{

}