<?php

namespace EventBundle\Repository;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDemandeEvent($id)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT e FROM EventBundle:Participants e 
              
              WHERE
                e.Evenement=:id and e.confirmation=false ")
            ->setParameter('id', $id)
            ->getResult();
    }
}