hotes_maisonshotes:
    resource: "@HotesBundle/Resources/config/routing/maisonshotes.yml"
    prefix:   /maisonshotes

hotes_homepage:
    path:     /
    defaults: { _controller: HotesBundle:Default:index }
hotes_afficher:
    path:     /afficher
    defaults: { _controller: HotesBundle:Default:Afficher }

hotes_ajoute:
  path:     /ajouter
  defaults: { _controller: HotesBundle:Default:AjouterHote }    